# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

# using chainlink and OpenZeppelin
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
  - OpenZeppelin/openzeppelin-contracts@4.0.0

# compiler settings
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0'

# exclude SafeMath when calculating test coverage
reports:
  exclude_contracts:
    - ERC20
    - ERC721
    - Ownable
    - MockEnsRegistry
    - MockPublicResolver
    - MockV3Aggregator

# automatically fetch contract sources from Etherscan
autofetch_sources: True
# environment settings
dotenv: .env
# change to trye to verify smart contracts
verify: False

# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar
    mock_pair: ['eth-usd', 'btc-usd', 'link-usd', 'bnb-usd']
    mock_price: [2000, 30000, 20, 300]
  mainnet:
    ens_registry: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'
  rinkeby:
    ens_registry: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

# wallets
wallets:
  from_key: ${PRIVATE_KEY}
  test_key: ${TEST_PUBLIC_KEY}